# Name of the workflow
name: csv-to-csvw example
# How the workflow should be triggered.
on:
  push:
    branches:
      - main
# Workflow action
jobs:
  generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload
    runs-on: ubuntu-latest
    steps:
      - name: csv-to-csvw action
        # csv-to-csvw action path. The latest version is always available at https://github.com/marketplace/actions/csv-to-csvw-action
        uses: GSS-Cogs/csv-to-csvw-action@v0.0.26-alpha
        # Configurations
        with:
          # Boolean indicating whether the outputs should be commited to the out folder (default is true).
          commit-outputs: true
          # Boolean indicating whether the outputs should be published to GitHub Pages (default is true).
          publish-to-gh-pages: true
