name: csv-to-csvw example
description: An example action showing how to use the csv-to-csvw action.
on:
  push:
    branches:
      - main
jobs:
  generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload
    steps: 
      - name: Build and Inspect
        uses: actions/csv-to-csvw-action