name: csv-to-csvw example

on:
  push:
    branches:
      - main

jobs:
  generate_csvw_from_csv_upload:
    name: Generate CSV-W from csv upload
    runs-on: ubuntu-latest
    steps: 
    - name: csv-to-csvw action
      uses: GSS-Cogs/csv-to-csvw-action@v0.0.10-alpha
      with-inputs:
        - publish-to-gh-pages: true
        - gh-pages-url: 
        
    
